### ISSUE TITLE
run_ags.sh not creating 

### ISSUE THREAD

**Issue by marschmi** [pereiramemo/AGS-and-ACN-tools#10]
Hi there! 

I'm excited to learn about your tool for AGS and ACN estimation. I'm trying to work through the sample data under [Getting Started](https://github.com/pereiramemo/AGS-and-ACN-tools/wiki/Getting-started) in the wiki. However, when I run the code below, it only produces two files `tara_023_srf_ags.tsv` and `tara_023_srf_orfs.faa`. Therefore, I do not have the input for calculating ACN. 

```
../../bin/AGS-and-ACN-tools/run_ags.sh data/TARA_023_SRF_redu2M.fna \
      tara_023_srf_ags_output \
      --min_length 100 \
      --sample_name tara_023_srf \
      --verbose t \
      --overwrite t \
      --nslots 10 \
      --save_complemenatry_data t
```

Do you have any advice on how to fix this? Thank you!

**Comment by pereiramemo** [comment]
Hi! 

When using the flag "--save_complementary_data" you should get these five files:
tara_023_srf_ags.tsv  
tara_023_srf_FBL.fna  
tara_023_srf_orfs.faa  
tara_023_srf_single_cogs_count.tsv  
tara_023_srf_uout.csv

Could you please save the standard output to a file and paste it here?
For example:
../../bin/AGS-and-ACN-tools/run_ags.sh data/TARA_023_SRF_redu2M.fna \
      tara_023_srf_ags_output \
      --min_length 100 \
      --sample_name tara_023_srf \
      --verbose t \
      --overwrite t \
      --nslots 10 \
      --save_complemenatry_data t > **file.log**

Thanks!

Emiliano

**Comment by marschmi** [comment]
Oh my, it looks like I have a silly typo. :flushed: 
I wrote --save_complemen**atry**_data t, instead of --save_complemen**tary**_data t   :sweat_smile: 
I don't know how I failed at copying over your documentation page!  :cold_sweat:
Sorry for the issue!

**Comment by pereiramemo** [comment]
OK. Thanks for letting me know.
