### ISSUE TITLE
How not to apply BBDuk?

### ISSUE THREAD

**Issue by dh23333** [pereiramemo/AGS-and-ACN-tools#11]
My data is clean and I don't need to trimme with BBDuk. So how to close these optional steps?

**Comment by pereiramemo** [comment]
Hi, 

Even if your data is clean, we recommend removing reads shorter than 120bp and trimming reads to 200bp (if longer), when using the ags tool. Anyway, the filtering is optional. To avoid it just set the minimum length to zero (i.e., --min_length 0) and do not use the --max_length flag. 

Cheers, 

Emiliano
