### ISSUE TITLE
SortMeRNA failed

### ISSUE THREAD

**Issue by gc26762524** [pereiramemo/AGS-and-ACN-tools#12]
Hi, I am running the demo dataset and I found an error when running the run_acn.sh with 

"${run_acn}" \
  tara_023_srf_ags_output/tara_023_srf_FBL.fna \
  tara_023_srf_ags_output/tara_023_srf_ags.tsv \
  tara_023_srf_acn_output \
  --sample_name tara_023_srf \
  --evalue 1e-10 \
  --min_identity 80 \
  --min_length 30 \
  --verbose t \
  --overwrite t \
  --nslots 2 \
  --save_complementary_data t

I got the error:

Identifying 16S rRNA genes ...
ERROR: -m [INT] must not exceed 1989 (Mbyte).
SortMeRNA failed

I am in Mac and have downloaded the docker images. Please advise if you have any suggestions. Thank you in advance.

**Comment by pereiramemo** [comment]
Hi, 

Other users also had this error. It is related to how Docker works in Mac. I am sorry, but the best solution is to use a Linux computer.

Best, 

Emiliano
