### ISSUE TITLE
Effect of fungi and viruses

### ISSUE THREAD

**Issue by wanxn518** [pereiramemo/AGS-and-ACN-tools#13]
Hello great developers, our macrogenome samples have sequences of higher abundance of fungi and viruses, when calculating the average genome size and average 16S copy number, do we need to remove these sequences first to avoid large errors？Hope to get your guidance.

**Comment by wanxn518** [comment]
Hello

Thank you very much for your reply, which is very helpful for our research. 
At the same time I have another problem, when I calculate the ags and acn, occasionally will show this error message：
```
~/apps/AGS-and-ACN-tools/run_ags.sh ../H3B11/H3B11.interleave.fa ../H3B11/H3B11.faa ../H3B11/H3B11-ags --sample_name H3B11 --overwrite t --save_complementary_data t #I provide the faa file predicted with FragGeneScanPlus
uproc_prot failed
```
Some samples of tasks submitted at the same time will run normally with results, but some samples will have the error message that they cannot run.
I don't know what the cause is, do you have any good suggestions ？

Best,
XiaoNan

**Comment by pereiramemo** [comment]
Hi,

I have a few questions:
1. Is it always failing to run for the same samples?
2. If it's consistently failing with the same samples, could you try to run
these using fraggenescanplusplus within the run_ags.sh tool?
3. Can you try to run it using --verbose?

Emiliano
