### ISSUE TITLE
rsync: recv_generator: mkdir "/output/tara_023_srf_ags_output" failed: Permission denied (13)

### ISSUE THREAD

**Issue by zpinocchio** [pereiramemo/AGS-and-ACN-tools#14]
Thanks  for your work!
I follow the Getting started document, download the data/TARA_023_SRF_redu2M.fna.gz and gunzip
but i run the command
`"${run_ags}" data/TARA_023_SRF_redu2M.fna tara_023_srf_ags_output \
  --min_length 100 \
  --sample_name tara_023_srf \
  --verbose t \
  --overwrite t \
  --nslots 2 \
  --save_complementary_data t`
I got this error
Run finished with 2 threads.
Annotating SCGs ...
rsync: recv_generator: mkdir "/output/tara_023_srf_ags_output" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]

**Comment by pereiramemo** [comment]
Hi!

Did you add your user to the docker group?  
https://docs.docker.com/engine/install/linux-postinstall/

Hope this helps. Please let me know otherwise.

Best, 

Emiliano

**Comment by zpinocchio** [comment]
add option `--privileged=true` in docker run seems work!
Thanks

**Comment by pereiramemo** [comment]
Thanks!
