### ISSUE TITLE
sortmerna failed

### ISSUE THREAD

**Issue by susheelbhanu** [pereiramemo/AGS-and-ACN-tools#3]
Hi, 

I tried the following, and I get the following error. From your TARA oceans example it is not clear if we are to first pre-run sortmerna on the sample. 

```./run_acn.sh B4.fna B4_ags.tsv B4_acs_output evalue 1e-10 --min_identity 80 --min_length 30 --verbose t --nslots 4 --save_complementary_data t
sormerna failed```
 Could you please clarify?

Thanks

**Comment by pereiramemo** [comment]
Could it be that the "--" (minus minus) is missing before the "evalue" flag?

Best, 

Emiliano

**Comment by susheelbhanu** [comment]
That seemed to have done the job. Thank you, and sorry I missed such a minor detail. :)
