### ISSUE TITLE
memory -m option of SortMeRNA error

### ISSUE THREAD

**Issue by brittanysuttner** [pereiramemo/AGS-and-ACN-tools#8]
Hello, I am using acn.sh on MacOS with Docker and running with TARA test data and get the following error (I tried with and without explicitely stating the --smrna_mem option and still get the same error):

./run_acn.sh tara_ags_output/tara_023_srf_FBL.fna tara_ags_output/tara_023_srf_ags.tsv tara_acn_output --evalue 1e-10   --min_identity 80   --min_length 30   --verbose t   --overwrite t   --nslots 2   --save_complementary_data t   --smrna_mem 1024
Unable to find image 'epereira/acn:latest' locally
latest: Pulling from epereira/acn
423ae2b273f4: Pull complete 
de83a2304fa1: Pull complete 
f9a83bce3af0: Pull complete 
b6b53be908de: Pull complete 
c38428f8001a: Pull complete 
74ca5d8a314e: Pull complete 
fd176dc9124e: Pull complete 
fe5a592d6031: Pull complete 
48a1c334397a: Pull complete 
2bde6447fd7a: Pull complete 
229602989b4b: Pull complete 
2791a3f3906d: Pull complete 
01ca4b6b4e64: Pull complete 
9e0af1d426c0: Pull complete 
58ef52b995e9: Pull complete 
0a8390a31b2c: Pull complete 
56a089dbf60d: Pull complete 
a45353e2dc59: Pull complete 
49db43483422: Pull complete 
7fd0473b9cdf: Pull complete 
12302c07b075: Pull complete 
64a1159ae245: Pull complete 
65185568e3bd: Pull complete 
c5f99cb58ace: Pull complete 
Digest: sha256:d8aeeeebbf83f3d25911edbf0554e41c0c5d4bc85342f86597f815eabdf0e0e1
Status: Downloaded newer image for epereira/acn:latest
Identifying 16S rRNA genes ...

ERROR: -m [INT] must not exceed 1989 (Mbyte).

SortMeRNA failed

**Comment by pereiramemo** [comment]
Hi!

Thanks for using our tools. 
Could please tell me what MacOS are you using?
A user had this issue once; however, I haven't bee able to reproduce it. It appears to be related to how Docker works in Mac. 
I am sorry but I don't have a real solution, just a workaround:
1. If possible use a Linux computer (Docker works better in Linux). 
2. Install and run the SortMeRNA tool on your computer, and the use the blast formatted output of this tool  to run the acn.sh tool (see https://github.com/pereiramemo/AGS-and-ACN-tools/wiki/Documentation#2-acnsh).

**Comment by pereiramemo** [comment]
Hi!

Thanks for using our tools. 
Could please tell me what MacOS are you using?
A user had this issue once, but I haven't been able to reproduce it. It appears to be related to how Docker works in Mac. 

I am sorry but I don't have a real solution, just two workarounds:
1. If possible use a Linux computer (also, Docker works better in Linux). 
2. If you can install and run the SortMeRNA tool on your Mac computer, you could use the blast formatted tabular output of this tool to run the acn.sh tool (see https://github.com/pereiramemo/AGS-and-ACN-tools/wiki/Documentation#2-acnsh). 

Let me know if this was clear enough or if you have other questions.

Best, 

Emiliano

**Comment by brittanysuttner** [comment]
Hello,
My version of MaOS is Sierra 10.12.6
Yes I have SortMeRNA output for my data and will try the workaround you
suggested. Thanks.

**Comment by pereiramemo** [comment]
Good! 
Just make sure the sortmerna blast output is tabulated like this: http://www.metagenomics.wiki/tools/blast/blastn-output-format-6

Best, 

Emiliano
