### ISSUE TITLE
wc inclueds newlines.

### ISSUE THREAD

**Issue by cErikson** [pereiramemo/AGS-and-ACN-tools#9]
wc in the line used to calculate total base count, counts newlines as well.

**Comment by pereiramemo** [comment]
Hi, 

This line?
BP_TOTAL=$(egrep -v "^>" "${INPUT_FNA}" | wc | awk '{ print $3-$1}')
New lines are subtracted. 

Cheers, 

Emiliano

**Comment by cErikson** [comment]
Yes, my version of `wc` does the following
```
>line1
ATCG
>line2
ATCG
```
